# Site settings
title: Bisonai
email: contact@bisonai.com
url: https://www.bisonai.com
description: "Bisonai - The next generation of artifical intelligence"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#fff'
  links: '#219ab3'

# Footer settings
footer: © Bisonai 2018

# Team names, titles and social links
people:
- name: Martin Kersner
  pic: 1
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/martinkersner
    - title: github
      url: https://github.com/martinkersner

# Build settings
markdown: kramdown
permalink: pretty
