# Site settings
title: Bisonai
email: contact@bisonai.com
url: //bisonai.com
description: "Bisonai - The next generation of artifical intelligence"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#fff'
  links: '#219ab3'

# Footer settings
footer: © Bisonai 2019

# Team names, titles and social links
team_list:
  - martin

# Build settings
markdown: kramdown
permalink: pretty
