# Site settings
title: BISON AI
email: contact@bisonai.com
url: https://www.bisonai.com
description: "BISON AI - Squeeze the maximum from your data"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Made with <span id="heart">&#10084;</span> in Gangnam

# Team names, titles and social links
people:
- name: Martin Keršner
  pic: 1
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/martinkersner
    - title: github
      url: https://github.com/martinkersner

- name: Cinyoung Hur
  pic: 2
  position: Co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/cinyounghur
    - title: github
      url: https://github.com/hurcy

- name: Saturnino Abril
  pic: 3
  position: Co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/saturnino-abril-166b176b
    - title: github
      url: https://github.com/saturninoabril

# Build settings
markdown: kramdown
permalink: pretty
